/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  time?: string;
  venue?: string;
  address?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigation?: Array<{
    _key: string;
  } & NavItem>;
  socialLinks?: Array<{
    _key: string;
  } & SocialLink>;
};

export type TroupePage = {
  _id: string;
  _type: "troupePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introQuote?: string;
  genesisImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  genesisText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  philosophyText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SpectaclesPage = {
  _id: string;
  _type: "spectaclesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introQuote?: string;
  explanationHeading?: string;
  explanationText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroSubtitle?: string;
  heroQuote?: string;
  artImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  artText?: string;
  quoteText?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "instagram" | "facebook" | "tiktok" | "youtube" | "other";
  url?: string;
};

export type NavItem = {
  _type: "navItem";
  label?: string;
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | Show | SanityImageCrop | SanityImageHotspot | Slug | SiteSettings | TroupePage | SpectaclesPage | HomePage | SocialLink | NavItem | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    heroImage {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  hotspot,  crop},    heroSubtitle,    heroQuote,    artImage {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  hotspot,  crop},    artText,    quoteText  }
export type HOME_PAGE_QUERY_RESULT = {
  heroImage: null;
  heroSubtitle: null;
  heroQuote: null;
  artImage: null;
  artText: null;
  quoteText: null;
} | {
  heroImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  heroSubtitle: string | null;
  heroQuote: string | null;
  artImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  artText: string | null;
  quoteText: string | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: SPECTACLES_PAGE_QUERY
// Query: *[_id == "spectaclesPage"][0]{    introQuote,    explanationHeading,    explanationText  }
export type SPECTACLES_PAGE_QUERY_RESULT = {
  introQuote: null;
  explanationHeading: null;
  explanationText: null;
} | {
  introQuote: string | null;
  explanationHeading: null;
  explanationText: null;
} | {
  introQuote: string | null;
  explanationHeading: string | null;
  explanationText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: TROUPE_PAGE_QUERY
// Query: *[_id == "troupePage"][0]{    introQuote,    genesisImage {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  hotspot,  crop},    genesisText,    philosophyText  }
export type TROUPE_PAGE_QUERY_RESULT = {
  introQuote: null;
  genesisImage: null;
  genesisText: null;
  philosophyText: null;
} | {
  introQuote: string | null;
  genesisImage: null;
  genesisText: null;
  philosophyText: null;
} | {
  introQuote: string | null;
  genesisImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  genesisText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  philosophyText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    navigation[]{ label, href },    socialLinks[]{ platform, url }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  navigation: null;
  socialLinks: null;
} | {
  navigation: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  socialLinks: Array<{
    platform: "facebook" | "instagram" | "other" | "tiktok" | "youtube" | null;
    url: string | null;
  }> | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: SHOWS_QUERY
// Query: *[_type == "show"] | order(date asc){    _id,    title,    "slug": slug.current,    date,    time,    venue,    address,    image {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  hotspot,  crop},    description  }
export type SHOWS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  time: string | null;
  venue: string | null;
  address: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  description: string | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: SHOW_BY_SLUG_QUERY
// Query: *[_type == "show" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    date,    time,    venue,    address,    image {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  hotspot,  crop},    description  }
export type SHOW_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  time: string | null;
  venue: string | null;
  address: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  description: string | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: SHOW_SLUGS_QUERY
// Query: *[_type == "show" && defined(slug.current)].slug.current
export type SHOW_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_id == \"homePage\"][0]{\n    heroImage {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  hotspot,\n  crop\n},\n    heroSubtitle,\n    heroQuote,\n    artImage {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  hotspot,\n  crop\n},\n    artText,\n    quoteText\n  }\n": HOME_PAGE_QUERY_RESULT;
    "\n  *[_id == \"spectaclesPage\"][0]{\n    introQuote,\n    explanationHeading,\n    explanationText\n  }\n": SPECTACLES_PAGE_QUERY_RESULT;
    "\n  *[_id == \"troupePage\"][0]{\n    introQuote,\n    genesisImage {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  hotspot,\n  crop\n},\n    genesisText,\n    philosophyText\n  }\n": TROUPE_PAGE_QUERY_RESULT;
    "\n  *[_id == \"siteSettings\"][0]{\n    navigation[]{ label, href },\n    socialLinks[]{ platform, url }\n  }\n": SITE_SETTINGS_QUERY_RESULT;
    "\n  *[_type == \"show\"] | order(date asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    date,\n    time,\n    venue,\n    address,\n    image {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  hotspot,\n  crop\n},\n    description\n  }\n": SHOWS_QUERY_RESULT;
    "\n  *[_type == \"show\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    date,\n    time,\n    venue,\n    address,\n    image {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  hotspot,\n  crop\n},\n    description\n  }\n": SHOW_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"show\" && defined(slug.current)].slug.current\n": SHOW_SLUGS_QUERY_RESULT;
  }
}

